<?php

namespace app\controllers;

use app\models\User;
use Yii;
use yii\filters\AccessControl;

abstract class SecuredController extends \yii\web\Controller
{

    public $userProfile;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ],
                'denyCallback' => function ($rule, $action) {
                    return $action->controller->redirect('/');
                }
            ]
        ];
    }


/*    public function beforeAction($action)
    {


        if ($id = Yii::$app->user->getId()) {
            $this->userProfile = User::findOne($id);
        } else {
            $this->userProfile = null;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }*/

}
